version: '3'
services:
  minio:
    image: minio/minio
    restart: always
    ports:
      - "9007:9000"
      - "9008:9001"
    volumes:
      - minio:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_USERNAME}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    command: server --console-address ":9001" /data

volumes:
  minio: