version: '3'
services:
  minio:
    image: minio/minio
    restart: always
    network:
      - bridge
    ports:
      - "9013:9000"
      - "9014:9001"
    volumes:
      - minio:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_USERNAME}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    command: server --console-address ":9001" /data

volumes:
  minio:

networks:
  bridge:
    name: jenkins_default
    external: true
