version: '3.6'
services:
  uptime:
    container_name: uptime
    image: louislam/uptime-kuma
    networks:
      - bridge
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - uptime-data:/app/data

volumes:
  uptime-data:

networks:
  bridge:
    name: jenkins_default
    external: true