- name: Setup stateful services
  hosts: _manual
  become: true
  tasks:
    - name: Create a uptime dir if it does not exist
      ansible.builtin.file:
        path: /uptime
        state: directory
        mode: '0755'

    - name: Copy file from host to machine
      copy:
        src: "{{ playbook_dir }}/docker-compose.yml"
        dest: /uptime/docker-compose.yml

    - name: Create and start services
      community.docker.docker_compose:
        project_src: /uptime/
      register: output

    - debug:
        var: output

    - name: Register middleware host with variable
      add_host:
        name: "MIDDLEWARE_HOST"
        SERVER_NAME: "status.*"
        PROXY_ADDRESS: "http://{{ ansible_default_ipv4.address }}:3001"

- name: Setup nginx config for jenkins
  hosts: _manager:_worker:_worker_gpu
  become: true
  vars:
    server_name: "{{ hostvars['MIDDLEWARE_HOST']['SERVER_NAME'] }}"
    proxy_address: "{{ hostvars['MIDDLEWARE_HOST']['PROXY_ADDRESS'] }}"
    use_https: true
    config: ["proxy_http_version 1.1;", "proxy_set_header   Upgrade $http_upgrade;", "proxy_set_header   Connection \"upgrade\";"]
  tasks: 
    - name: Create a /nginx directory
      ansible.builtin.file:
        path: /nginx
        state: directory
        mode: '0755'

    - name: Create a /nginx/conf.d directory
      ansible.builtin.file:
        path: /nginx/conf.d
        state: directory
        mode: '0755'

    - name: generate a nginx conf file
      template:
        src: "~/devops/templates/nginx.conf.j2"
        dest: /nginx/conf.d/uptime.conf

    - name: Run nginx reload command on every running nginx container
      shell: |
        docker exec $(docker ps -q -f name=nginx) nginx -s reload
