version: '3.6'
services:
  jenkins:
      image: jenkins/jenkins:lts
      restart: unless-stopped
      privileged: true
      user: root
      ports:
        - 9000:8080
      container_name: jenkins
      volumes:
        - jenkins_volume:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/local/bin/docker:/usr/local/bin/docker

volumes:
  jenkins_volume: