version: '3.6'
services:
  db:
    container_name: "${identifier}-bff-db"
    image: samagragovernance/postgres:1.0.1-pg15
    restart: always
    ports:
      - "5446:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  
  redis:
    container_name: "${identifier}-bff-redis"
    image: redis:latest
    ports:
      - '6383:6379'
    command: [ 'redis-server', '--appendonly', 'yes' ]
    hostname: redis
    volumes:
      - redis:/data
      - redis_conf:/usr/local/etc/redis/redis.conf

volumes:
  db:
  redis:
  redis_conf:
