version: '3.8'
services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - /database/loki:/etc/loki
      - loki:/loki
    command: -config.file=/etc/loki/loki-config.yaml
  
volumes:
  loki:
