version: '3.8'
services:
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    networks:
      - bridge
    volumes:
      - /var/log:/var/log
      - /exporters/promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml:ro
    command: -config.file=/etc/promtail/promtail-config.yaml
    restart: always
    deploy:
      mode: global

  nodeexporter:
    image: prom/node-exporter:v1.6.1
    container_name: nodeexporter
    networks:
      - bridge
    ports:
      - target: 9100
        published: 9100
        protocol: tcp
        mode: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: always
    deploy:
      mode: global

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.1
    container_name: cadvisor
    networks:
      - bridge
    privileged: true
    ports:
      - target: 8080
        published: 8082
        protocol: tcp
        mode: host
    devices:
      - /dev/kmsg:/dev/kmsg
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      # - /cgroup:/cgroup:ro
    deploy:
      mode: global

networks:
  bridge:
    name: communication
    external: true
