- name: Copy Exporters Directory
  hosts: _manager:_worker:_worker_gpu:_manual
  become: true
  tasks:
    - name: Copy Exporters Directory
      copy:
        src: "{{ playbook_dir }}"
        dest: "/"

- name: Deployment for Stateful VM
  hosts: _manual
  become: true
  tasks:
    - name: Deploy Exporters on Stateful VM
      community.docker.docker_compose:
        project_src: /exporters/
      register: output

- name: Deployment for Swarm
  hosts: _manager
  become: true
  tasks:
    - name: Deploy Exporters on Swarm
      docker_stack:
        compose: "/exporters/docker-compose.yml"
        name: exporters
        state: present

- name: Update docker daemon file for GPU Nodes
  hosts: _worker_gpu
  become: true
  tasks:
    - name: Configure docker daemon
      copy:
        src: "{{ playbook_dir }}/exporters/docker/gpu/daemon.json"
        dest: "/etc/docker/daemon.json"
    
    - name: Restart Docker
      ansible.builtin.service:
        name: docker
        state: restarted

- name: Update docker daemon file for Non-GPU Nodes
  hosts: _worker:_manager:_manual
  become: true
  tasks:
    - name: Configure docker daemon
      copy:
        src: "{{ playbook_dir }}/exporters/docker/non-gpu/daemon.json"
        dest: "/etc/docker/daemon.json"

    - name: Restart Docker
      ansible.builtin.service:
        name: docker
        state: restarted


